name: Python application

# Вказуємо, на які події реагуємо (наприклад, пуш на гілку main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Вказуємо середовище для виконання

    steps:
      # Крок для отримання коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Крок для налаштування Python середовища
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Крок для встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run tests
        run: |
          python -m unittest discover test


